# Generated by Django 3.0.5 on 2020-04-29 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_auto_20200429_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='dispatch_address',
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='user_accounts.Customer'),
        ),
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Address to which items will be delivered.'), (2, 'Address from where items will be dispatched.')], default=1),
        ),
    ]
