# Generated by Django 3.0.5 on 2020-04-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=30)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('no_of_bids', models.IntegerField()),
                ('final_bidding_price', models.FloatField()),
                ('buyer_id', models.IntegerField()),
                ('transaction_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('bidding_amount', models.FloatField()),
                ('bid_finalized_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('coins_exchange_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('dispatch_address_id', models.IntegerField()),
                ('delivery_address_id', models.IntegerField()),
                ('coins', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('start_price', models.FloatField()),
                ('sale_status', models.BooleanField()),
                ('approval_status', models.BooleanField()),
                ('seller_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_status', models.BooleanField()),
                ('delivery_status', models.BooleanField()),
                ('company_profits', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UnapprovedEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('penalty_amount', models.FloatField()),
                ('penalty_reason', models.CharField(max_length=200)),
            ],
        ),
    ]
