# Generated by Django 3.0.5 on 2020-04-15 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('virtdibs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_id',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
