# Generated by Django 3.0.5 on 2020-04-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtdibs', '0002_auto_20200416_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
